version: "2"

services:

  producer:
    build: ./producer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: topic_test

  consumer:
    build: ./consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: topic_test

networks:
  default:
    external:
      name: kafka-network